#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
