#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '26i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo -i 
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
