#!/usr/bin/env bash
# Install nginx on remote server

apt-get -y update
apt-get -y install nginx

sudo sed i '43 s/#//' etc /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo service nginx start
