#!/usr/bin/env bash
# Handling signals
pgrep -f 100-process_and_pid_file >> /var/run/holbertonscript.pid
sig_term() {
	   echo "I hate the kill command"
	   rm /var/run/holbertonscript.pid
	   exit
}
sig_int() {
	  echo "Y U no love me?!"
	  exit
}
sig_quit() {
	   rm /var/run/holbertonscript.pid
	   exit
}
trap sig_term SIGTERM
trap sig_int SIGINT
trap sig_quit SIGQUIT

for (( ; ; ))
do
	echo "To infinity and beyond"
	sleep 2
done
