#!/usr/bin/env bash
# Excuting nginx web server as user nginx
sudo pkill -o apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
