#!/usr/bin/env bash
# Excuting nginx web server as user nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx --commmand "service nginx restart"
