#!/usr/bin/env bash
# Executing nginx web server as user nginx
sudo pkill -o apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
